name: Helm Chart CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint ./app-chart

      - name: Helm Template
        run: helm template test-app ./app-chart

      - name: Dry Run Install
        run: helm install test-app ./app-chart --dry-run
