name: Package Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Chart
        run: |
          helm package app-chart
          mkdir charts
          mv *.tgz charts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: charts/
