name: Helm PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  helm-pr-check:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Helm chart
        run: |
          helm lint .

      - name: Package Helm chart
        run: |
          helm package .
