name: Helm PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  helm-pr-check:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Setup Kind cluster
        uses: helm/kind-action@v1

      - name: Lint Helm chart
        run: |
          helm lint . -f Values.yml

      - name: Package Helm chart
        run: |
          helm package .

      - name: Deploy sample nginx app
        run: |
          helm install demo-app . -f Values.yml

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc

      - name: Run Helm tests
        run: |
          helm test demo-app
