name: Helm Semantic Version Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm Chart
        run: helm lint .

      - name: Package Helm Chart
        run: helm package .

      - name: Get chart version
        id: chart_version
        run: |
          VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git tag v${{ steps.chart_version.outputs.version }}
          git push origin v${{ steps.chart_version.outputs.version }}
