name: Helm Semantic Version Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint . -f Values.yml

      - name: Package Helm chart
        run: helm package . 

      - name: Bump Chart version
        run: |
          CURRENT_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEW_PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" Chart.yaml

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Chart.yaml
          git commit -m "bump chart version to $NEW_VERSION"

      - name: Get version from Chart.yaml
        id: chart_version
        run: |
         VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
         echo "Chart version: $VERSION"
         echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v${{ steps.chart_version.outputs.version }}
          git push origin v${{ steps.chart_version.outputs.version }}